### ISSUE TITLE
Strict Hunger - feature request

### ISSUE THREAD

**Issue by TheUtopianPlayz** [Xenophilicy/FoodEffects#1]
if u have full hunger then it still gives the effect but doesnt eat the item

**Comment by Xenophilicy** [comment]
Hello there,

This is intended behavior of the plugin due to the way item interactions are handled in PMMP, therefore this is not considered a bug. If you would like an option to require there be room in your hunger bar in order to interact (eat) the item (or food), then I can gladly add that for you and push an update. Please get back to me whether you'd like this to be added.

If you're curious, it would be something like this in the config.yml file:
```yaml
# This is an option to force players to have available space in the hunger bar in order to use the effects on a food item
Strict-Hunger: true
```

Note that this option would apply to all items, not just ones to be considered food.

Thanks!
-Xeno

**Comment by TheUtopianPlayz** [comment]
Ya that would be great, thanks xeno

**Comment by Xenophilicy** [comment]
@TheUtopianPlayz,

I have discovered that this is actually a bug with pocketmine because the event is never actually cancelled if the player's food bar is full (when food attribute is 20). I have opened an issue that you can view [here](https://github.com/pmmp/PocketMine-MP/issues/3293). Once this is fixed, you won't have this issue anymore. 

I might still add an option for non-food items to be used with the plugin, therefore bypassing the food bar altogether. I'll let you know about when you can expect it to function properly.

**Comment by Xenophilicy** [comment]
It was decided to not be changed because of other food items like golden apples. I am pushing an update to Poggit with this feature added. You can view it [here](https://poggit.pmmp.io/p/FoodEffects/1.0.1). Thanks!
